node {
      def mvnHome
    
    
    

   
  
        stage('Prepare') {
            
              git url: 'https://github.com/iamjoydip95/spring-petclinic.git', branch:'main'
              mvnHome = tool 'mvn' 
            
        }
        
        stage('Build') {
           
            if(isUnix()) {
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
              }
              else {
              bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
              }
            
        }
        
stage('Load Docker Image'){

if (isUnix()) {

sh "minikube image load spring-petclinic-final"
} else {

bat(/minikube image load spring-petclinic-final/)
}

}
stage('Kubernetes deployment'){

if (isUnix()) {

sh "kubectl apply -f k8s/deployment.yaml"
} 
else {

bat("kubectl apply -f k8s/deployment.yaml")
}

}
    
}
